name: Update github myprofile

on: 
  workflow_dispatch:  # 支持手动触发
  page_build:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        cd ./github_myprofile_updater
        python3 update.py
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "cyanlaser@stu.pku.edu.cn"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/clownrat6/clownrat6.git"
        git add README.md
        git add images
        git commit -m "update my description automatically"
        git push "${remote_repo}" HEAD:main --force
